INSERT INTO `navi` VALUES (2, 0, 0, 'm', 'Datei', NULL, NULL, NULL);
INSERT INTO `navi` VALUES (3, 2, 0, 'i', 'Neumachen macht viel Laune', NULL, NULL, 'http://www.spiegel.de/');
INSERT INTO `navi` VALUES (4, 2, 1, 'i', 'Der Niko ist der Obermeister!!!!!', NULL, NULL, 'http://www.slashdot.org/');
INSERT INTO `navi` VALUES (5, 2, 2, 'i', 'Speichern', NULL, NULL, 'http://www.heise.de/');
INSERT INTO `navi` VALUES (6, 2, 3, 's', NULL, NULL, NULL, NULL);
INSERT INTO `navi` VALUES (7, 2, 4, 'i', 'Beenden', NULL, NULL, 'javascript:alert(''Fort bisch!'');');
INSERT INTO `navi` VALUES (8, 0, 1, 'm', 'Bearbeiten', NULL, NULL, NULL);
INSERT INTO `navi` VALUES (9, 8, 0, 'm', 'Einfuegen als', NULL, NULL, NULL);
INSERT INTO `navi` VALUES (10, 9, 0, 'i', 'Text', NULL, NULL, 'javascript:alert(''Text!'');');
INSERT INTO `navi` VALUES (11, 9, 1, 'i', 'HTML', NULL, '', 'http://w3.org/');
INSERT INTO `navi` VALUES (12, 0, 2, 'm', 'Konto', NULL, '{BADGER_ROOT}/modules/moduleTests/navi/account.png', NULL);
INSERT INTO `navi` VALUES (13, 12, 0, 'i', 'Abbuchen', NULL, NULL, '{BADGER_ROOT}/modules/account/transfer.php');
INSERT INTO `navi` VALUES (14, 0, 3, 'i', 'Ausloggen', NULL, '{BADGER_ROOT}/modules/moduleTests/navi/logout.png', 'javascript:alert(''Raus mit dir!'');');
