<form name="UserSettings" method="post" action="{BADGER_ROOT}/core/UserSettingsAdmin/UserSettingsAdmin.php">
	<fieldset>
		<legend>$FsHeading</ledgend>
		<br>
			<table>
			<tr>
				<td>$TemplateLabel</td>
				<td>$TemplateField</td>
			</tr>
			<tr>
				<td>$LanguageLabel</td>
				<td>$LanguageField</td>
			<tr>
				<td>$DateFormatLabel</td>
				<td>$DateFormatField</td>
			</tr>
			<tr>
				<td>$SeperatorsLabel</td>
				<td>$SeperatorsField</td>
			</tr>
			<tr>
				<td>$MaxLoginLabel</td>
				<td>$MaxLoginField</td>
			</tr>
			<tr>
				<td>$LockOutTimeLabel</td>
				<td>$LockOutTimeField</td>
			</tr>
			</tr>
			<tr>
				<td>$StartPageLabel</td>
				<td>$StartPageField</td>
			</tr>
			</tr>
			<tr>
				<td>$SessionTimeLabel</td>
				<td>$SessionTimeField</td>
			</tr>
		</table>
	</fieldset>
		<br/>
	<fieldset>
		<legend>$PWFormLabel</ledgend>
		<br/>
		<table>
			<tr>
				<td>$OldPwLabel</td>
				<td>$OldPwField</td>
			</tr>
			<tr>
				<td>$NewPwLabel</td>
				<td>$NewPwField</td>
			<tr>
				<td>$ConfPwLabel</td>
				<td>$ConfPwField</td>
			</tr>
		</table>
	$Feedback
	</fieldset>
		<table>
			<tr>
				<td></td>
				<td>$btnSubmit</td>
			</tr>
		</table>
</form>